### ISSUE TITLE
CPU affinity

### ISSUE THREAD

**Issue by aaron-lohmann** [wschuell/repodepo#4]
Hi,

first of all Thank you for the amazing work! 

I am trying to rerun your repo in https://github.com/wschuell/repo_datasets but I get an error here: 

`db.add_filler(commit_info.CommitsFiller())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/path/repo_datasets/src/repodepo/repodepo/fillers/commit_info.py", line 40, in __init__
    self.workers = len(psutil.Process().cpu_affinity())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Process' object has no attribute 'cpu_affinity'`

Do you know what might cause this and how I can potentially fix that? Again, thank you! Best Aaron. If you do not have time to answer, I appreciate a short message that you will not have time to address it.

**Comment by aaron-lohmann** [comment]
Ah, it seems that this might be due to me working on MacOS. Did you work on Linux implementing this? Then I might just try it out on a Linux machine myself.

**Comment by wschuell** [comment]
Hi Aaron, happy to see someone interested in the lib! :)
Yes I used only on Linux, and some collaborators used windows. If you set the workers argument to a value it will not make the call to this function (returning the number of available CPUs). If you know of any similar way to get that number in MacOS please tell me i ll implement the fix

**Comment by aaron-lohmann** [comment]
Perfect, that fixed it! Thanks

**Comment by wschuell** [comment]
Fixed on branch develop: if `psutil.cpu_affinity` is not available, trying `os.cpu_count` and if still failing defaulting to 1 core.
