### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by aaron-lohmann** [wschuell/repodepo#5]
Hi

as in the other issue: I am trying to rerun the code in your other repo. Though, it seems even though I supply valid API keys in env. variables, I still get the error that the keys are invalid. 

Can you confirm that this code still works for you and this has nothing to do with some updates in the APIs etc.? 

Best
Aaron

Again: Thank you!

**Comment by wschuell** [comment]
Did you check the value in os.environ['GITHUB_API_KEY'] from within the code? I typically load them through ~/.repo_tools/github_api_keys.txt. Also did you set several or just one? I never tested with several in the env var, but several in the txt file works.

**Comment by aaron-lohmann** [comment]
I think because you renamed the repo from repo_tools to repodepo the path pointed in the wrong directory. So that seems sorted. Though, I seem to have issues with the premissions of the token. Even though I have the read:user scope on Github it returns that this scope is missing. 

I will play around with it and test it next week, but if you have suggestions, please feel free! 

Thanks.

**Comment by wschuell** [comment]
To check that everything is in order, you can do 2 things:
 - Check that the scopes are indeed what you wanted, checking the header 'X-OAuth-Scopes' of the command:
```
curl -i -H 'Content-Type: application/json' -X POST -d '{"query": "query {user(login: \"wschuell\") {login} rateLimit{resetAt cost remaining}}"}' https://api.github.com/graphql  -H "Authorization: token <APIKEY>"
```
- Check if the API key is indeed loaded by repodepo:
```
import repodepo
from repodepo.fillers import github_gql

f = github_gql.ForksGQLFiller(data_folder='datafolder')
f.set_api_keys()

print(f.api_keys)

```

**Comment by aaron-lohmann** [comment]
It seems the issue was that I created my keys too powerful. I gave the permission user which should also include read:user but then I got the invalid response. So it seems that I have to adjust my key accordingly.

**Comment by aaron-lohmann** [comment]
Everything appears to be working now in terms of the key settings. Thanks for all the help. Will close this issue now.

**Comment by wschuell** [comment]
Great! BTW if you have any other questions that are not issues per se (e.g. research wise) or just want to chat about repodepo usage don't hesitate to contact me by email (you can find it on https://www.csh.ac.at/researcher/william-schueller/ )
