### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by aaron-lohmann** [wschuell/repodepo#6]
Hi, sorry for repeatedly opening new issues. 

With what kind of system did you use to generate the final large data set? 
I setup a 8GB Ram, i5, Thinkpad X1 Carbon (2020) with Linux Mint and roughly 240 GB of disk space hoping I could run the version where the package argument is _None_. 

My Python script got killed unfortunately and I am now sceptical whether it will end up working out. So if you could let me know what your system specs were, that would be great.

**Comment by wschuell** [comment]
I ran it on my workstation with 48GB of RAM, probably less is needed but 8GB is definitely low. Disk space for all the repos is also low on your side, what is taking most of the space is cloning all repos, and for Rust you should probably allocate around 1TB to be comfortable. For the dataset late 2022 it was around 200-250GB, and in march 2023 it was around 340 GB. You will also need typically a dozen API keys (from friends/colleagues) to not be limited too much by the API query limit. And even with enough API keys, the whole process can take 2-3weeks. If you provide more info about where the process gets killed I can give you hints how to limit RAM usage there. It should just slow down a bit the process but still be possible.
